In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('Input/Data.xlsx')
df.head(3)

,\rho(g/cm^3),T_c(K),T_f(K),c_b(ppm),3S_{tr1}(1),3S_{tr2}(2),\Sigma_{a1}(3),\Sigma_{a2}(4),nuS_{f1}(5),nuS_{f2}(6),\Sigma_{f1}(7),\Sigma_{f2}(8),\Sigma_{1->2}(9),k_{inf}(10),\sigma_{a2}^{Xe},\sigma_{a2}^{Sm}
0,0.7235,575.0,1027.0,600.0,0.661853,2.568298,0.009376,0.085584,0.006677,0.133250,0.002620,0.054750,0.017392,1.261041,1072970.0,35421.398
1,0.7750,448.0,1043.0,1500.0,0.679602,2.874687,0.009581,0.098339,0.006723,0.139256,0.002636,0.057218,0.018726,1.174265,1141000.0,36147.801
2,0.9125,370.5,1418.0,750.0,0.727336,3.668742,0.009908,0.102815,0.006844,0.153823,0.002681,0.063203,0.022463,1.249619,1308480.0,39214.000

In [3]:
df.describe()

,\rho(g/cm^3),T_c(K),T_f(K),c_b(ppm),3S_{tr1}(1),3S_{tr2}(2),\Sigma_{a1}(3),\Sigma_{a2}(4),nuS_{f1}(5),nuS_{f2}(6),\Sigma_{f1}(7),\Sigma_{f2}(8),\Sigma_{1->2}(9),k_{inf}(10),\sigma_{a2}^{Xe},\sigma_{a2}^{Sm}
count,257.000000,257.000000,257.000000,257.000000,257.000000,257.000000,257.000000,257.000000,257.000000,257.000000,257.000000,257.000000,257.000000,257.000000,2.570000e+02,257.000000
mean,0.773742,448.491808,1043.838306,1493.967349,0.679230,2.879487,0.009514,0.097856,0.006698,0.138663,0.002627,0.056974,0.018717,1.177139,1.124386e+06,35423.659751
std,0.158780,89.316810,430.718000,863.720860,0.053920,0.790229,0.000402,0.011233,0.000158,0.009800,0.000058,0.004026,0.004395,0.086005,1.195160e+05,2841.132233
min,0.502148,294.210910,298.859410,11.718750,0.586982,1.505131,0.008622,0.076091,0.006372,0.117360,0.002506,0.048221,0.011126,1.005264,8.587990e+05,29207.199000
25%,0.637500,371.710910,673.859380,750.000000,0.631098,2.204620,0.009225,0.089572,0.006571,0.131596,0.002581,0.054070,0.014993,1.106373,1.034060e+06,33246.301000
50%,0.772852,448.000000,1043.000000,1488.281000,0.678348,2.874687,0.009518,0.097073,0.006716,0.138722,0.002634,0.056998,0.018734,1.172133,1.124950e+06,35566.801000
75%,0.910352,525.500000,1412.141000,2238.281000,0.725984,3.566347,0.009804,0.105296,0.006834,0.144896,0.002677,0.059535,0.022463,1.245992,1.204050e+06,37580.500000
max,1.047852,601.789120,1787.141000,2988.281000,0.774060,4.406140,0.010476,0.130769,0.006941,0.165624,0.002716,0.068052,0.026528,1.384922,1.427190e+06,41929.301000

In [4]:
# отнормируем все на max
from sklearn.preprocessing import MaxAbsScaler
transformer = MaxAbsScaler().fit(df)

In [5]:
df_norm = pd.DataFrame(data=transformer.transform(df), columns=list(df))
df_norm

,\rho(g/cm^3),T_c(K),T_f(K),c_b(ppm),3S_{tr1}(1),3S_{tr2}(2),\Sigma_{a1}(3),\Sigma_{a2}(4),nuS_{f1}(5),nuS_{f2}(6),\Sigma_{f1}(7),\Sigma_{f2}(8),\Sigma_{1->2}(9),k_{inf}(10),\sigma_{a2}^{Xe},\sigma_{a2}^{Sm}
0,0.690460,0.955484,0.574661,0.200784,0.855041,0.582891,0.894982,0.654467,0.961967,0.804532,0.964537,0.804532,0.655592,0.910550,0.751806,0.844789
1,0.739608,0.744447,0.583614,0.501961,0.877971,0.652427,0.914623,0.752004,0.968602,0.840795,0.970656,0.840798,0.705893,0.847893,0.799473,0.862113
2,0.870829,0.615664,0.793446,0.250980,0.939638,0.832643,0.945764,0.786234,0.986026,0.928747,0.986937,0.928747,0.846762,0.902303,0.916823,0.935241
3,0.608387,0.873229,0.373781,0.752941,0.816401,0.488980,0.874049,0.703277,0.946781,0.764683,0.950142,0.764683,0.566524,0.814101,0.687627,0.774098
4,0.673998,0.680055,0.688530,0.125490,0.848092,0.587512,0.899065,0.682380,0.959470,0.862365,0.962177,0.862365,0.635221,0.924417,0.825048,0.873012
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252,0.610438,0.613652,0.213128,0.325490,0.815011,0.512777,0.843042,0.695177,0.947707,0.840140,0.951206,0.840140,0.578421,0.897941,0.780744,0.817283
253,0.872879,0.871217,0.632793,0.827451,0.940357,0.788830,0.954934,0.840421,0.984651,0.821929,0.985457,0.821929,0.845892,0.770720,0.778726,0.861996
254,0.741659,0.742435,0.842626,0.074510,0.880058,0.663899,0.922091,0.684965,0.969591,0.872624,0.971617,0.872624,0.706195,0.939847,0.849109,0.907420
255,0.479217,1.000000,0.422961,0.576471,0.758316,0.341598,0.839292,0.606006,0.919361,0.710392,0.924163,0.710392,0.426393,0.832381,0.603457,0.700434
256,0.480242,0.743441,0.713119,0.284314,0.760553,0.354067,0.856427,0.608692,0.919326,0.758223,0.924012,0.758223,0.422465,0.861015,0.671176,0.745169

In [6]:
df_norm.describe()

,\rho(g/cm^3),T_c(K),T_f(K),c_b(ppm),3S_{tr1}(1),3S_{tr2}(2),\Sigma_{a1}(3),\Sigma_{a2}(4),nuS_{f1}(5),nuS_{f2}(6),\Sigma_{f1}(7),\Sigma_{f2}(8),\Sigma_{1->2}(9),k_{inf}(10),\sigma_{a2}^{Xe},\sigma_{a2}^{Sm}
count,257.000000,257.000000,257.000000,257.000000,257.000000,257.000000,257.000000,257.000000,257.000000,257.000000,257.000000,257.000000,257.000000,257.000000,257.000000,257.000000
mean,0.738408,0.745264,0.584083,0.499942,0.877491,0.653517,0.908172,0.748311,0.964957,0.837214,0.967103,0.837214,0.705550,0.849968,0.787832,0.844843
std,0.151529,0.148419,0.241010,0.289036,0.069658,0.179347,0.038362,0.085899,0.022780,0.059168,0.021385,0.059168,0.165667,0.062101,0.083742,0.067760
min,0.479217,0.488894,0.167228,0.003922,0.758316,0.341598,0.823034,0.581877,0.918092,0.708590,0.922562,0.708590,0.419397,0.725864,0.601741,0.696582
25%,0.608387,0.617676,0.377060,0.250980,0.815309,0.500352,0.880554,0.684965,0.946781,0.794547,0.950142,0.794547,0.565171,0.798871,0.724543,0.792913
50%,0.737558,0.744447,0.583614,0.498039,0.876351,0.652427,0.908590,0.742327,0.967559,0.837570,0.969600,0.837570,0.706195,0.846353,0.788227,0.848256
75%,0.868779,0.873229,0.790168,0.749020,0.937892,0.809404,0.935909,0.805206,0.984651,0.874847,0.985457,0.874847,0.846762,0.899684,0.843651,0.896283
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [7]:
features = ['\\rho(g/cm^3)',
 'T_c(K)',
 'T_f(K)',
 'c_b(ppm)']

In [8]:
target = ['3S_{tr1}(1)',
 '3S_{tr2}(2)',
 '\\Sigma_{a1}(3)',
 '\\Sigma_{a2}(4)',
 'nuS_{f1}(5)',
 'nuS_{f2}(6)',
 '\\Sigma_{f1}(7)',
 '\\Sigma_{f2}(8)',
 '\\Sigma_{1->2}(9)',
 'k_{inf}(10)',
 '\\sigma_{a2}^{Xe}',
 '\\sigma_{a2}^{Sm}']

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df_norm[features],
                                                    df_norm[target],
                                                    test_size=0.33,
                                                    random_state=42)

In [10]:
X = X_train
Y = y_train

In [11]:
import numpy
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasRegressor
import tensorflow as tf

def create_model():

    # create model
    model = Sequential()
    model.add(Dense(4, input_dim=4, activation='tanh'))
    model.add(Dense(12, kernel_initializer='normal'))

    optimizer = tf.keras.optimizers.RMSprop(learning_rate = 0.001, rho = 0.99, momentum = 0.85, epsilon=1e-09)
    
    # Compile model
    model.compile(loss='mse', optimizer=optimizer)
    return model

In [12]:
model = create_model()
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 4)                 20
_________________________________________________________________
dense_1 (Dense)              (None, 12)                60
=================================================================
Total params: 80
Trainable params: 80
Non-trainable params: 0
_________________________________________________________________

In [13]:
# Обучение модели

EPOCHS = 1500
batch_size = 10

history = model.fit(
  X, Y,
  epochs=EPOCHS, batch_size = batch_size,verbose=0)

In [14]:
hist = pd.DataFrame(history.history)
hist['epoch'] = history.epoch
hist.tail(10)

          loss  epoch
1490  0.000055   1490
1491  0.000057   1491
1492  0.000053   1492
1493  0.000053   1493
1494  0.000051   1494
1495  0.000057   1495
1496  0.000060   1496
1497  0.000056   1497
1498  0.000053   1498
1499  0.000061   1499

In [15]:
import statsmodels as statsmodels
import statsmodels.api as sm

In [16]:
# тестовые значения целевых функций
df_y_test_real = pd.DataFrame(data=y_test.values, columns=target)

In [17]:
# предсказанные значения на тестовой выборке
df_y_test_predict = pd.DataFrame(data=model.predict(X_test), columns=target)

In [18]:
RMSPE = statsmodels.tools.eval_measures.rmspe(df_y_test_real, df_y_test_predict)
RMSPE

array([0.03769816, 0.10853937, 0.1010904 , 0.1718099 , 0.03517268,
       0.06430956, 0.0342073 , 0.06430886, 0.07521868, 0.12171502,
       0.1081179 , 0.14529121])

In [19]:
pd.DataFrame(data=RMSPE, index = [target], columns = ['RMSPE'])

                     RMSPE
3S_{tr1}(1)       0.037698
3S_{tr2}(2)       0.108539
\Sigma_{a1}(3)    0.101090
\Sigma_{a2}(4)    0.171810
nuS_{f1}(5)       0.035173
nuS_{f2}(6)       0.064310
\Sigma_{f1}(7)    0.034207
\Sigma_{f2}(8)    0.064309
\Sigma_{1->2}(9)  0.075219
k_{inf}(10)       0.121715
\sigma_{a2}^{Xe}  0.108118
\sigma_{a2}^{Sm}  0.145291

In [23]:
X_test_time = X_test.sample(n=1_000_000, replace=True)

In [26]:
X_test_time = X_test_time.to_numpy()

In [40]:
%%time

model.predict(X_test_time)

Wall time: 10.2 s

array([[0.77468646, 0.4185513 , 0.8362794 , ..., 0.83225965, 0.7097244 ,
        0.7458339 ],
       [0.7972479 , 0.46293473, 0.84040976, ..., 0.93242055, 0.7280871 ,
        0.80668014],
       [0.7583149 , 0.37287885, 0.8601107 , ..., 0.88914454, 0.71910024,
        0.7650609 ],
       ...,
       [0.9778645 , 0.92983085, 0.9477984 , ..., 0.86958927, 0.92245114,
        0.94192857],
       [0.77920365, 0.42510152, 0.85421836, ..., 0.87867117, 0.72555625,
        0.77396613],
       [0.9260929 , 0.7823527 , 0.92287946, ..., 0.7965637 , 0.80200756,
        0.85647726]], dtype=float32)

In [42]:
%%time

print(2+2)

4
Wall time: 0 ns